language: objective-c
osx_image: xcode7
xcode_project: Framework/LLDynamicLaunchScreen.xcodeproj
xcode_scheme: LLDynamicLaunchScreen
before_install:
- brew update
- brew upgrade xctool
script:
- xctool -project Framework/LLDynamicLaunchScreen.xcodeproj -scheme YYModel build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
after_success:
- bash <(curl -s https://codecov.io/bash)
